import os
import argparse
import json

def main():
    parser = argparse.ArgumentParser(description="Export theme code tokens for Flutter, TailwindCSS, SwiftUI, Jetpack Compose, and React.")
    parser.add_argument("--name", default="App", help="App Name")
    parser.add_argument("--primary", default="#16A34A", help="Primary Brand Color (HEX)")
    parser.add_argument("--secondary", default="#101820", help="Secondary Charcoal Color (HEX)")
    parser.add_argument("--accent", default="#D4A017", help="Accent Gold Color (HEX)")
    parser.add_argument("--dark", default="#0C3B2E", help="Dark Background Color (HEX)")
    parser.add_argument("--light", default="#F8FAFC", help="Light Background Color (HEX)")
    parser.add_argument("--output", default="./theme_export", help="Output Directory")

    args = parser.parse_args()
    os.makedirs(args.output, exist_ok=True)
    
    p_hex = args.primary.replace("#", "")
    s_hex = args.secondary.replace("#", "")
    a_hex = args.accent.replace("#", "")
    d_hex = args.dark.replace("#", "")
    l_hex = args.light.replace("#", "")

    # 1. FLUTTER (app_colors.dart & app_theme.dart)
    flutter_dir = os.path.join(args.output, "flutter")
    os.makedirs(flutter_dir, exist_ok=True)

    flutter_colors = f'''// Generated by Antigravity Brand Kit Creator v1.1.0
import 'package:flutter/material.dart';

class AppColors {{
  static const Color primary = Color(0xFF{p_hex});
  static const Color secondary = Color(0xFF{s_hex});
  static const Color accent = Color(0xFF{a_hex});
  static const Color darkBackground = Color(0xFF{d_hex});
  static const Color lightBackground = Color(0xFF{l_hex});
  static const Color surface = Color(0xFFFFFFFF);
  static const Color textPrimary = Color(0xFF{s_hex});
  static const Color textSecondary = Color(0xFF64748B);
}}
'''
    with open(os.path.join(flutter_dir, "app_colors.dart"), "w", encoding="utf-8") as f:
        f.write(flutter_colors)

    flutter_theme = f'''// Generated by Antigravity Brand Kit Creator v1.1.0
import 'package:flutter/material.dart';
import 'app_colors.dart';

class AppTheme {{
  static ThemeData get lightTheme {{
    return ThemeData(
      useMaterial3: true,
      primaryColor: AppColors.primary,
      scaffoldBackgroundColor: AppColors.lightBackground,
      colorScheme: ColorScheme.fromSeed(
        seedColor: AppColors.primary,
        primary: AppColors.primary,
        secondary: AppColors.secondary,
        surface: AppColors.surface,
        background: AppColors.lightBackground,
      ),
      fontFamily: 'Poppins',
    );
  }}

  static ThemeData get darkTheme {{
    return ThemeData(
      useMaterial3: true,
      primaryColor: AppColors.primary,
      scaffoldBackgroundColor: AppColors.darkBackground,
      colorScheme: ColorScheme.fromSeed(
        seedColor: AppColors.primary,
        brightness: Brightness.dark,
        primary: AppColors.primary,
        secondary: AppColors.accent,
        background: AppColors.darkBackground,
      ),
      fontFamily: 'Poppins',
    );
  }}
}}
'''
    with open(os.path.join(flutter_dir, "app_theme.dart"), "w", encoding="utf-8") as f:
        f.write(flutter_theme)

    # 2. SWIFTUI (AppTheme.swift)
    swiftui_dir = os.path.join(args.output, "swiftui")
    os.makedirs(swiftui_dir, exist_ok=True)
    swiftui_code = f'''// Generated by Antigravity Brand Kit Creator v1.1.0
import SwiftUI

public struct AppTheme {{
    public static let primary = Color(hex: "{args.primary}")
    public static let secondary = Color(hex: "{args.secondary}")
    public static let accent = Color(hex: "{args.accent}")
    public static let darkBackground = Color(hex: "{args.dark}")
    public static let lightBackground = Color(hex: "{args.light}")
}}

extension Color {{
    init(hex: String) {{
        let hex = hex.trimmingCharacters(in: CharacterSet.alphanumerics.inverted)
        var int: UInt64 = 0
        Scanner(string: hex).scanHexInt64(&int)
        let r, g, b: UInt64
        switch hex.count {{
        case 6: (r, g, b) = (int >> 16, int >> 8 & 0xFF, int & 0xFF)
        default: (r, g, b) = (1, 1, 1)
        }}
        self.init(.sRGB, red: Double(r)/255, green: Double(g)/255, blue: Double(b)/255, opacity: 1)
    }}
}}
'''
    with open(os.path.join(swiftui_dir, "AppTheme.swift"), "w", encoding="utf-8") as f:
        f.write(swiftui_code)

    # 3. JETPACK COMPOSE (Color.kt & Theme.kt)
    compose_dir = os.path.join(args.output, "compose")
    os.makedirs(compose_dir, exist_ok=True)
    compose_colors = f'''// Generated by Antigravity Brand Kit Creator v1.1.0
package com.brand.theme

import androidx.compose.ui.graphics.Color

val PrimaryColor = Color(0xFF{p_hex})
val SecondaryColor = Color(0xFF{s_hex})
val AccentColor = Color(0xFF{a_hex})
val DarkBackgroundColor = Color(0xFF{d_hex})
val LightBackgroundColor = Color(0xFF{l_hex})
'''
    with open(os.path.join(compose_dir, "Color.kt"), "w", encoding="utf-8") as f:
        f.write(compose_colors)

    # 4. TAILWIND & CSS VARIABLES (tailwind.config.js & theme.css)
    web_dir = os.path.join(args.output, "web")
    os.makedirs(web_dir, exist_ok=True)
    
    tailwind_code = f'''// Generated by Antigravity Brand Kit Creator v1.1.0
module.exports = {{
  theme: {{
    extend: {{
      colors: {{
        brand: {{
          primary: '{args.primary}',
          secondary: '{args.secondary}',
          accent: '{args.accent}',
          dark: '{args.dark}',
          light: '{args.light}'
        }}
      }},
      fontFamily: {{
        sans: ['Poppins', 'Inter', 'sans-serif'],
        serif: ['Cormorant Garamond', 'serif']
      }}
    }}
  }}
}}
'''
    with open(os.path.join(web_dir, "tailwind.config.js"), "w", encoding="utf-8") as f:
        f.write(tailwind_code)

    css_vars = f'''/* Generated by Antigravity Brand Kit Creator v1.1.0 */
:root {{
  --color-primary: {args.primary};
  --color-secondary: {args.secondary};
  --color-accent: {args.accent};
  --color-dark-bg: {args.dark};
  --color-light-bg: {args.light};
  --font-family-primary: 'Poppins', 'Inter', sans-serif;
}}
'''
    with open(os.path.join(web_dir, "theme.css"), "w", encoding="utf-8") as f:
        f.write(css_vars)

    # 5. REACT / JSON TOKENS (tokens.json)
    tokens_json = {
      "brand": {
        "name": args.name,
        "colors": {
          "primary": args.primary,
          "secondary": args.secondary,
          "accent": args.accent,
          "dark": args.dark,
          "light": args.light
        }
      }
    }
    with open(os.path.join(web_dir, "tokens.json"), "w", encoding="utf-8") as f:
        json.dump(tokens_json, f, indent=2)

    print(f"Theme code tokens exported for Flutter, SwiftUI, Compose, Tailwind, and React in '{args.output}'!")

if __name__ == "__main__":
    main()
