import os
import argparse

def main():
    parser = argparse.ArgumentParser(description="Export theme code tokens for Flutter, TailwindCSS, and CSS Variables.")
    parser.add_argument("--name", default="App", help="App Name")
    parser.add_argument("--primary", default="#16A34A", help="Primary Color")
    parser.add_argument("--secondary", default="#101820", help="Secondary Color")
    parser.add_argument("--accent", default="#D4A017", help="Accent Color")
    parser.add_argument("--output", default="./theme_export", help="Output Directory")

    args = parser.parse_args()
    os.makedirs(args.output, exist_ok=True)
    
    # 1. Export Flutter AppColors (app_colors.dart)
    flutter_code = f'''// Generated by Antigravity Brand Kit Creator
import 'package:flutter/material.dart';

class AppColors {{
  static const Color primary = Color(0xFF{args.primary.replace("#", "")});
  static const Color secondary = Color(0xFF{args.secondary.replace("#", "")});
  static const Color accent = Color(0xFF{args.accent.replace("#", "")});
  static const Color background = Color(0xFFF8F9FA);
  static const Color surface = Color(0xFFFFFFFF);
  static const Color textPrimary = Color(0xFF101820);
}}
'''
    with open(os.path.join(args.output, "app_colors.dart"), "w", encoding="utf-8") as f:
        f.write(flutter_code)
        
    # 2. Export Tailwind Config (tailwind.config.js)
    tailwind_code = f'''// Generated by Antigravity Brand Kit Creator
module.exports = {{
  theme: {{
    extend: {{
      colors: {{
        brand: {{
          primary: '{args.primary}',
          secondary: '{args.secondary}',
          accent: '{args.accent}',
          light: '#F8F9FA',
          dark: '#0C3B2E'
        }}
      }},
      fontFamily: {{
        poppins: ['Poppins', 'sans-serif']
      }}
    }}
  }}
}}
'''
    with open(os.path.join(args.output, "tailwind.config.js"), "w", encoding="utf-8") as f:
        f.write(tailwind_code)

    print(f"Successfully exported Theme Tokens for Flutter & Tailwind in '{args.output}'!")

if __name__ == "__main__":
    main()
