import os
import json
import argparse
from PIL import Image

def main():
    parser = argparse.ArgumentParser(description="Generate native Android, iOS, and Web app icons & splash screen assets.")
    parser.add_argument("--icon", required=True, help="Path to 1024x1024 master app icon PNG")
    parser.add_argument("--primary", default="#16A34A", help="Primary brand color (HEX)")
    parser.add_argument("--background", default="#F8FAFC", help="Splash background color (HEX)")
    parser.add_argument("--output", default="./native_assets", help="Output directory")

    args = parser.parse_args()
    
    if not os.path.exists(args.icon):
        print(f"Error: Master icon not found at {args.icon}")
        return

    master = Image.open(args.icon)
    os.makedirs(args.output, exist_ok=True)

    p_hex = args.primary.replace("#", "")
    bg_hex = args.background.replace("#", "")

    # 1. ANDROID RES FOLDER STRUCTURE
    android_dir = os.path.join(args.output, "android", "res")
    mipmap_sizes = {
        "mipmap-mdpi": 48,
        "mipmap-hdpi": 72,
        "mipmap-xhdpi": 96,
        "mipmap-xxhdpi": 144,
        "mipmap-xxxhdpi": 192,
    }
    
    for folder, dim in mipmap_sizes.items():
        target_folder = os.path.join(android_dir, folder)
        os.makedirs(target_folder, exist_ok=True)
        resized = master.resize((dim, dim), Image.Resampling.LANCZOS)
        resized.save(os.path.join(target_folder, "ic_launcher.png"))

    # Android Launch Background XMLs & Colors
    drawable_dir = os.path.join(android_dir, "drawable")
    drawable_v21_dir = os.path.join(android_dir, "drawable-v21")
    values_dir = os.path.join(android_dir, "values")
    os.makedirs(drawable_dir, exist_ok=True)
    os.makedirs(drawable_v21_dir, exist_ok=True)
    os.makedirs(values_dir, exist_ok=True)

    launch_bg_xml = f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by Antigravity Brand Kit Creator v1.1.0 -->
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@color/launch_background_color" />
    <item>
        <bitmap
            android:gravity="center"
            android:src="@mipmap/ic_launcher" />
    </item>
</layer-list>
'''
    with open(os.path.join(drawable_dir, "launch_background.xml"), "w", encoding="utf-8") as f:
        f.write(launch_bg_xml)
    with open(os.path.join(drawable_v21_dir, "launch_background.xml"), "w", encoding="utf-8") as f:
        f.write(launch_bg_xml)

    colors_xml = f'''<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="launch_background_color">#{bg_hex}</color>
    <color name="brand_primary">#{p_hex}</color>
</resources>
'''
    with open(os.path.join(values_dir, "colors.xml"), "w", encoding="utf-8") as f:
        f.write(colors_xml)

    # 2. IOS XCODE ASSET CATALOG (AppIcon.appiconset)
    ios_dir = os.path.join(args.output, "ios", "Runner", "Assets.xcassets", "AppIcon.appiconset")
    os.makedirs(ios_dir, exist_ok=True)

    ios_sizes = [
        ("Icon-App-20x20@2x.png", 40),
        ("Icon-App-20x20@3x.png", 60),
        ("Icon-App-29x29@2x.png", 58),
        ("Icon-App-29x29@3x.png", 87),
        ("Icon-App-40x40@2x.png", 80),
        ("Icon-App-40x40@3x.png", 120),
        ("Icon-App-60x60@2x.png", 120),
        ("Icon-App-60x60@3x.png", 180),
        ("Icon-App-1024x1024@1x.png", 1024),
    ]

    for fname, dim in ios_sizes:
        resized = master.resize((dim, dim), Image.Resampling.LANCZOS)
        resized.save(os.path.join(ios_dir, fname))

    ios_json = {
      "images": [
        { "size": "20x20", "idiom": "iphone", "filename": "Icon-App-20x20@2x.png", "scale": "2x" },
        { "size": "20x20", "idiom": "iphone", "filename": "Icon-App-20x20@3x.png", "scale": "3x" },
        { "size": "29x29", "idiom": "iphone", "filename": "Icon-App-29x29@2x.png", "scale": "2x" },
        { "size": "29x29", "idiom": "iphone", "filename": "Icon-App-29x29@3x.png", "scale": "3x" },
        { "size": "40x40", "idiom": "iphone", "filename": "Icon-App-40x40@2x.png", "scale": "2x" },
        { "size": "40x40", "idiom": "iphone", "filename": "Icon-App-40x40@3x.png", "scale": "3x" },
        { "size": "60x60", "idiom": "iphone", "filename": "Icon-App-60x60@2x.png", "scale": "2x" },
        { "size": "60x60", "idiom": "iphone", "filename": "Icon-App-60x60@3x.png", "scale": "3x" },
        { "size": "1024x1024", "idiom": "ios-marketing", "filename": "Icon-App-1024x1024@1x.png", "scale": "1x" }
      ],
      "info": { "version": 1, "author": "antigravity-brand-kit-creator" }
    }
    with open(os.path.join(ios_dir, "Contents.json"), "w", encoding="utf-8") as f:
        json.dump(ios_json, f, indent=2)

    # 3. WEB & PWA ASSETS
    web_dir = os.path.join(args.output, "web")
    os.makedirs(web_dir, exist_ok=True)

    master.resize((32, 32), Image.Resampling.LANCZOS).save(os.path.join(web_dir, "favicon.png"))
    master.resize((180, 180), Image.Resampling.LANCZOS).save(os.path.join(web_dir, "apple-touch-icon.png"))

    web_manifest = {
      "name": "App",
      "short_name": "App",
      "start_url": ".",
      "display": "standalone",
      "background_color": f"#{bg_hex}",
      "theme_color": f"#{p_hex}",
      "icons": [
        { "src": "favicon.png", "sizes": "32x32", "type": "image/png" },
        { "src": "apple-touch-icon.png", "sizes": "180x180", "type": "image/png" }
      ]
    }
    with open(os.path.join(web_dir, "manifest.json"), "w", encoding="utf-8") as f:
        json.dump(web_manifest, f, indent=2)

    print(f"Native Android res, iOS AppIcon.appiconset, and Web manifest assets generated in '{args.output}'!")

if __name__ == "__main__":
    main()
